### ISSUE TITLE
Avoid Flashes of bright light when loading pages

### ISSUE THREAD

**Issue by ImpossibleReality** [gubareve/synergy-addons#11]
I noticed that when you load any page on student view, the scripts may load after window.onload causing a bright flash of the regular (white) theme before dark mode has kicked in. I also noticed that if you set the "run_at" key of the content script to "document_start", the scripts will load before the regular theme, causing the regular theme to be more predominate. Hopefully there is a fix for this!
[here is a helpful link explaining the run-time of content scripts.](https://developer.chrome.com/extensions/content_scripts#run_time)

**Comment by gubareve** [comment]
Interesting. My main concern is some content scripts edit objects which have to be loaded. Is there a way to only apply this to certain content scripts.

**Comment by ImpossibleReality** [comment]
I was thinking of putting a css file in manifest.json instead of some of the scripts that would run at document_start (after css is loaded but before DOM is created). I seem to be having issues with the CSS applying to all of the selectors... We could possible change what goes to the browser in the background.js, or at least delay the loading of the window...
