### ISSUE TITLE
Fix icon not loading on webstore

### ISSUE THREAD

**Issue by ImpossibleReality** [gubareve/synergy-addons#14]
The image is blank on both the chrome webstore, and in chrome dev tools.

**Comment by gubareve** [comment]
Yeah im going to start testing fixes.

**Comment by gubareve** [comment]
I have contacted support:

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/D41-JUwWWio

**Comment by gubareve** [comment]
I think I may have a fix. CWS only works on weekdays so I need to wait til monday. I think the reason the icon is not showing is that there is a bug in the new dashboard that makes icon disappear. Come monday im going to try publishing using the old dashboard.

**Comment by gubareve** [comment]
I have a working fix. It will apply in the V3 update.
