### ISSUE TITLE
Fix The Assignments Tab

### ISSUE THREAD

**Issue by gubareve** [gubareve/synergy-addons#17]
Currently if you go to the assignments tab while using the extension you get some un-recognize-able text as shown:

![image](https://user-images.githubusercontent.com/24500411/77816927-1d6e8e00-7084-11ea-9388-a7b3709c4b57.png)

Can we fix this so the text is white instead of black?

**Comment by ImpossibleReality** [comment]
I will work on this...

**Comment by ImpossibleReality** [comment]
Done:
![image](https://user-images.githubusercontent.com/50127946/77818114-27e15580-708d-11ea-8445-8cf19cbec14e.png)
