### ISSUE TITLE
Change Login Title Color

### ISSUE THREAD

**Issue by gubareve** [gubareve/synergy-addons#21]
Currently when logging on to [Student Vue](https://wa-bsd405-psv.edupoint.com/PXP2_Login.aspx?Logout=1) while using the extension, the text at the top blends in and can not be read. Can we change this text color to white?

![image](https://user-images.githubusercontent.com/24500411/77838505-76dcc880-7129-11ea-9da5-352e8badd17e.png)

**Comment by rishipudipeddi** [comment]
Fixed
