### ISSUE TITLE
Add [Student Id Hidden] message to the student info card.

### ISSUE THREAD

**Issue by gubareve** [gubareve/synergy-addons#22]
We should add [Student Id Hidden] to the student id card instead of just removing the student id. Here is a mockup:

![image](https://user-images.githubusercontent.com/24500411/77842563-89b2c580-7148-11ea-9b72-0b1029891dee.png)

**Comment by rishipudipeddi** [comment]
okay i can do that

**Comment by rishipudipeddi** [comment]
I fixed it
![image](https://user-images.githubusercontent.com/49598383/77856288-eba41700-71aa-11ea-9206-f13cca086c71.png)
