### ISSUE TITLE
Message Contrast

### ISSUE THREAD

**Issue by liulinden** [gubareve/synergy-addons#6]
I was on StudentVue, enjoying the addons, when I noticed I had a new message. I opened it, but I could barely read the text. This is due to a poor color choice. The background behind the text was an extremely light shade of gray while the message text placed directly atop the background was white. 
See the below screenshot of part of one message that I had been sent.
<img width="95" alt="contrast" src="https://user-images.githubusercontent.com/50274080/77595949-daf85600-6eb7-11ea-8d94-d580307256cb.png">
Though it is possible to make out the content of the text (i.e. Good Evening,) it is still a pain to have to squint at the screen, especially with long messages. 
This issue can be easily fixed through a more fit choice of background or text color. 
Thank you for your time.

**Comment by gubareve** [comment]
Hi, I will look into this and reply after I'm done. Thanks for reporting this. 👍

**Comment by gubareve** [comment]
After alot of time, I came up with this:

```
document.querySelector('tr.MessageContent > td').style.backgroundColor = '#323232'
```

This script will change the background color on the currently selected message.

I will add this to messages.js and close this issue when I am done.

**Comment by liulinden** [comment]
Thanks!

**Comment by rishipudipeddi** [comment]
Thanks for the feedback Linden

**Comment by gubareve** [comment]
@thexpiredpear changed messages.js in fc6bf575b3313f0b5b8e387462cee0e901f09589 to automatically run above code whenever the table is clicked in response to your issue. This is what the new message looks like.

![image](https://user-images.githubusercontent.com/24500411/77606131-f96c4a80-6ed3-11ea-9eb2-78821471ac76.png)
Here is the new message text. I have uploaded this to master and will upload this to the Chrome Web Store within the next week. (You will be able to test it next week)

Thank You,
Evan G

**Comment by ImpossibleReality** [comment]
I Fixed This. Now it totally works, even without clicking the table. I injected some CSS.
